import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Gitmoji Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1>Feature 1</h1>
      {/* <div>:construction: Work in progress</div> */}
      {/* <div>:art: Improve structure / format of the code</div>  */}
      {/* <div>:zap: Improve query performance</div> */}
      {/* <h1>:fire: Remove code or files</h1> */}
      <div>:sparkles: Feature 2</div>
      {/* <div>:sparkles: New plugin</div>  */}
      {/* <div>:lipstick: PLD UI improvements</div>  */}
      {/* <div>:ambulance: Security fixes 4.0.7</div>  */}
      {/* <div>:arrow_up: Upgrade Snap</div> */}
      </main>
    </>
  )
}
